[project]
name = "trading-news-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-functions>=1.24.0",
    "dotenv>=0.9.9",
    "news-please>=1.6.16",
    "pandas>=3.0.0",
]
